name = "ACEAX Sample Compat"
prefix = "ChangeMe001" # <- Use a custom prefix, change also in addons\main\$PBOPREFIX$ and config.cpp
author = "YourName"  # <- Your name 
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp",
    "logo.paa"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]